// Map features take from https://wiki.openstreetmap.org/wiki/Map_features

const AMENITY_KEY = 'amenity';
export const AMENITY = {
  bank: `"${AMENITY_KEY}"="bank"`,
  bar: `"${AMENITY_KEY}"="bar"`,
  college: `${AMENITY_KEY}=college`,
  ice_cream: `"${AMENITY_KEY}"="ice_cream"`,
};

const FEATURES_DESCRIPTION = {
  AMENITY: {
    SUSTENANCE: {
      BAR: `${AMENITY.bar} (https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbar)`,
    },
    EDUCATION: {
      COLLEGE: `${AMENITY.college} (https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcollege)`,
    },
  },
};

export const FEATURES = [
  {
    key: 'atm',
    value1: 'atm=yes',
    value2: 'amenity=atm',
    value3: '',
    value4: '',
    value5: '',
    category: 'amenity',
    description_es: '',
    description_en: '',
    info: 'https://wiki.openstreetmap.org/wiki/Tag:amenity%3Datm',
  },
  {
    key: 'bank',
    value1: 'amenity=bank',
    value2: '',
    value3: '',
    value4: '',
    value5: '',
    category: 'amenity',
    description_es: '',
    description_en: '',
    info: 'https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbank',
  },
  {
    key: 'bar',
    value1: 'amenity=bar',
    value2: '',
    value3: '',
    value4: '',
    value5: '',
    category: 'amenity',
    description_es: '',
    description_en: '',
    info: 'https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbar',
  },
  {
    key: 'biergarten',
    value1: 'amenity=biertgarten',
    value2: 'biertgarten=yes',
    value3: '',
    value4: '',
    value5: '',
    category: 'amenity',
    description_es: '',
    description_en: '',
    info: 'https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbiergarten',
  },
  {
    key: 'cafe',
    value1: 'amenity=cafe',
    value2: '',
    value3: '',
    value4: '',
    value5: '',
    category: 'amenity',
    description_es: '',
    description_en: '',
    info: 'https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcafe',
  },
  {
    key: 'fast_food',
    value1: 'amenity=fast_food',
    value2: '',
    value3: '',
    value4: '',
    value5: '',
    category: 'amenity',
    description_es: '',
    description_en: '',
    info: 'https://wiki.openstreetmap.org/wiki/Eo:Tag:amenity%3Dfast_food',
  },
  {
    key: 'ice_cream',
    value1: 'amenity=ice_cream',
    value2: '',
    value3: '',
    value4: '',
    value5: '',
    category: 'amenity',
    description_es: '',
    description_en: '',
    info: 'https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dice_cream',
  },
  {
    key: 'pub',
    value1: 'amenity=pub',
    value2: '',
    value3: '',
    value4: '',
    value5: '',
    category: 'amenity',
    description_es: '',
    description_en: '',
    info: 'https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpub',
  },
  {
    key: 'restaurant',
    value1: 'amenity=restaurant',
    value2: '',
    value3: '',
    value4: '',
    value5: '',
    category: 'amenity',
    description_es: '',
    description_en: '',
    info: 'https://wiki.openstreetmap.org/wiki/Tag:amenity%3Drestaurant',
  },
  {
    key: 'college',
    value1: 'amenity=college',
    value2: '',
    value3: '',
    value4: '',
    value5: '',
    category: 'amenity',
    description_es: 'Campus o edificios de un instituto de educación superior',
    description_en:
      'Campus or buildings of an institute of Further Education (aka continuing education)',
    info: 'https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcollege',
  },
  {
    key: 'driving_school',
    value1: 'amenity=driving_school',
    value2: '',
    value3: '',
    value4: '',
    value5: '',
    category: 'amenity',
    description_es:
      'Autoescuela para poder sacar licencia de diferentes vehículos motorizados',
    description_en: 'Driving School which offers motor vehicle driving lessons',
    info: 'https://wiki.openstreetmap.org/wiki/Tag:amenity%3Ddriving_school',
  },
  {
    key: 'library',
    value1: 'amenity=library',
    value2: '',
    value3: '',
    value4: '',
    value5: '',
    category: 'amenity',
    description_es:
      'Una biblioteca pública (municipal, universitaria,…) para sacar libros en préstamo.',
    description_en:
      'A public library (municipal, university, …) to borrow books from.',
    info: '',
  },
  {
    key: 'school',
    value1: 'amenity=school',
    value2: '',
    value3: '',
    value4: '',
    value5: '',
    category: 'amenity',
    description_es: '',
    description_en: '',
    info: 'https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dschool',
  },
  {
    key: 'university',
    value1: 'amenity=university',
    value2: '',
    value3: '',
    value4: '',
    value5: '',
    category: 'amenity',
    description_es: '',
    description_en: '',
    info: '',
  },
  {
    key: 'education',
    value1: 'amenity=university',
    value2: 'amenity=school',
    value3: 'amenity=college',
    value4: 'amenity=music_school',
    value5: 'amenity=language_school',
    category: 'amenity',
    description_es: '',
    description_en: '',
    info: '',
  },
  {
    key: 'language',
    value1: 'amenity=language_school',
    value2: '',
    value3: '',
    value4: '',
    value5: '',
    category: 'amenity',
    description_es: '',
    description_en: '',
    info: 'https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dlanguage_school',
  },
  {
    key: 'bus',
    value1: 'amenity=bus_station',
    value2: 'public_transport=station',
    value3: '',
    value4: '',
    value5: '',
    category: 'amenity',
    description_es: '',
    description_en: '',
    info: '',
  },
  {
    key: 'car_wash',
    value1: 'amenity=car_wash',
    value2: '',
    value3: '',
    value4: '',
    value5: '',
    category: 'amenity',
    description_es: '',
    description_en: '',
    info: 'https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcar_wash',
  },
  {
    key: 'gasoline',
    value1: 'amenity=fuel',
    value2: '',
    value3: '',
    value4: '',
    value5: '',
    category: 'amenity',
    description_es: '',
    description_en: '',
    info: '',
  },
  {
    key: 'parking',
    value1: 'amenity=parking',
    value2: 'highway=service',
    value3: 'service=parking_aisle',
    value4: '',
    value5: '',
    category: 'amenity',
    description_es: '',
    description_en: '',
    info: '',
  },
];
